-- SECTION Create database with IF EXISTS Checking
USE master
GO

IF NOT EXISTS (
    SELECT name
        FROM sys.databases
        WHERE name = N'ResourceMaster'
)
CREATE DATABASE ResourceMaster
GO
-- !SECTION Done || Create database with IF EXISTS checking

-- SECTION Drop tables with IF EXISTS checking
USE ResourceMaster
GO

DROP TABLE IF EXISTS mengandung
DROP TABLE IF EXISTS menghasilkan_produk_tambang
DROP TABLE IF EXISTS menghasilkan_produk_kebun
DROP TABLE IF EXISTS menghasilkan_produk_hutan
DROP TABLE IF EXISTS menjalin
DROP TABLE IF EXISTS dimiliki_oleh
DROP TABLE IF EXISTS dimanfaatkan_oleh
DROP TABLE IF EXISTS UNSUR
DROP TABLE IF EXISTS PRODUK_TAMBANG
DROP TABLE IF EXISTS MINYAK_MENTAH
DROP TABLE IF EXISTS PRODUK_PERKEBUNAN
DROP TABLE IF EXISTS PRODUK_PERHUTANAN
DROP TABLE IF EXISTS INSTALASI_PENGOLAHAN_AIR
DROP TABLE IF EXISTS PEMBANGKIT_LISTRIK
DROP TABLE IF EXISTS KERJASAMA
DROP TABLE IF EXISTS PERUSAHAAN
DROP TABLE IF EXISTS IZIN_USAHA
DROP TABLE IF EXISTS SITUS_AIR
DROP TABLE IF EXISTS TAMBANG
DROP TABLE IF EXISTS RIG_PENGEBORAN
DROP TABLE IF EXISTS KEBUN
DROP TABLE IF EXISTS HUTAN
DROP TABLE IF EXISTS SITUS_SDA
DROP TABLE IF EXISTS KABUPATEN_KOTA
GO

-- !SECTION Done || Drop tables with IF EXISTS checking

-- SECTION Define relational tables
CREATE TABLE KABUPATEN_KOTA (
    KdKabKot INT IDENTITY(1,1) PRIMARY KEY,
    Nama VARCHAR(50) NOT NULL,
    Provinsi VARCHAR(50) NOT NULL
)

CREATE TABLE SITUS_SDA (
    KdSitus INT IDENTITY(1,1) PRIMARY KEY,
    NamaSitus VARCHAR(50) NOT NULL,
    KlasifikasiSDA VARCHAR(10) NOT NULL,
    KoordinatLong FLOAT NOT NULL,
    KoordinatLat FLOAT NOT NULL,
    Jumlah INT NOT NULL,
    Satuan VARCHAR(30) NOT NULL,
    KdKabKot INT NOT NULL
    CONSTRAINT FK_KabKotSITUSSDA FOREIGN KEY (KdKabKot)
        REFERENCES KABUPATEN_KOTA (KdKabKot) ON DELETE NO ACTION ON UPDATE NO ACTION
)

CREATE TABLE HUTAN (
    KdSitusHutan INT PRIMARY KEY,
    JenisHutan VARCHAR(50) NOT NULL
    CONSTRAINT FK_DisjointHUTAN FOREIGN KEY (KdSitusHutan)
        REFERENCES SITUS_SDA (KdSitus) ON DELETE NO ACTION ON UPDATE NO ACTION
)

CREATE TABLE KEBUN (
    KdSitusKebun INT PRIMARY KEY,
    JenisHasil VARCHAR(50) NOT NULL
    CONSTRAINT FK_DisjointKEBUN FOREIGN KEY (KdSitusKebun)
        REFERENCES SITUS_SDA (KdSitus) ON DELETE NO ACTION ON UPDATE NO ACTION
)

CREATE TABLE RIG_PENGEBORAN (
    KdSitusPengeboran INT PRIMARY KEY,
    KlasifikasiLokasi VARCHAR(50) NOT NULL
    CONSTRAINT FK_DisjointRIGPENGEBORAN FOREIGN KEY (KdSitusPengeboran)
        REFERENCES SITUS_SDA (KdSitus) ON DELETE NO ACTION ON UPDATE NO ACTION
)

CREATE TABLE TAMBANG (
    KdSitusTambang INT PRIMARY KEY,
    KlasifikasiLokasi VARCHAR(50) NOT NULL
    CONSTRAINT FK_DisjointTAMBANG FOREIGN KEY (KdSitusTambang)
        REFERENCES SITUS_SDA (KdSitus) ON DELETE NO ACTION ON UPDATE NO ACTION
)

CREATE TABLE SITUS_AIR (
    KdSitusAir INT PRIMARY KEY,
    JenisSitus VARCHAR(50) NOT NULL,
    TingkatKeasaman FLOAT NOT NULL,
    OksigenTerlarut FLOAT NOT NULL,
    Salinitas FLOAT NOT NULL,
    Alkalinitas FLOAT NOT NULL
    CONSTRAINT FK_DisjointSITUSAIR FOREIGN KEY (KdSitusAir)
        REFERENCES SITUS_SDA (KdSitus) ON DELETE NO ACTION ON UPDATE NO ACTION
)

CREATE TABLE IZIN_USAHA (
    KdIzin INT IDENTITY(1,1) PRIMARY KEY,
    NamaIzin VARCHAR(50) NOT NULL,
    JenisIzin VARCHAR(50) NOT NULL
)

CREATE TABLE PERUSAHAAN (
    KdPerusahaan INT IDENTITY(1,1) PRIMARY KEY,
    Nama VARCHAR(50) NOT NULL,
    Pemilik VARCHAR(50) NOT NULL,
    Website VARCHAR(50) NOT NULL,
    Email VARCHAR(50) NOT NULL,
    KotaKantorPusat VARCHAR(50) NOT NULL
)

CREATE TABLE KERJASAMA (
    KdKS INT IDENTITY(1,1) PRIMARY KEY,
    JenisKerjaSama VARCHAR(50) NOT NULL
)

CREATE TABLE PEMBANGKIT_LISTRIK (
    KdInstalasi INT IDENTITY(1,1) PRIMARY KEY,
    NamaInstalasi VARCHAR(50) NOT NULL,
    KapasitasProd INT NOT NULL,
    KdSitusAir INT NOT NULL,
    KdPerusahaan INT NOT NULL,
    CONSTRAINT FK_KdSitusAirPEMBANGKITLISTRIK FOREIGN KEY (KdSitusAir)
        REFERENCES SITUS_AIR (KdSitusAir) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT FK_KdPerusahaanPEMBANGKITLISTRIK FOREIGN KEY (KdPerusahaan)
        REFERENCES PERUSAHAAN (KdPerusahaan) ON DELETE NO ACTION ON UPDATE NO ACTION
)

CREATE TABLE INSTALASI_PENGOLAHAN_AIR (
    KdInstalasi INT IDENTITY(1,1) PRIMARY KEY,
    NamaInstalasi VARCHAR(50) NOT NULL,
    LokasiKota VARCHAR(50) NOT NULL,
    KdSitusAir INT NOT NULL,
    KdPerusahaan INT NOT NULL,
    CONSTRAINT FK_KdSitusAirINSTALASIPENGOLAHANAIR FOREIGN KEY (KdSitusAir)
        REFERENCES SITUS_AIR (KdSitusAir) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT FK_KdPerusahaanINSTALASIPENGOLAHANAIR FOREIGN KEY (KdPerusahaan)
        REFERENCES PERUSAHAAN (KdPerusahaan) ON DELETE NO ACTION ON UPDATE NO ACTION
)

CREATE TABLE PRODUK_PERHUTANAN (
    KdProdHutan INT IDENTITY(1,1) PRIMARY KEY,
    NamaProduk VARCHAR(50) NOT NULL,
    NamaIlmiah VARCHAR(50) NOT NULL,
    JenisPerhutanan VARCHAR(8) NOT NULL,
)

CREATE TABLE PRODUK_PERKEBUNAN (
    KdProdKebun INT IDENTITY(1,1) PRIMARY KEY,
    NamaProduk VARCHAR(50) NOT NULL,
    NamaIlmiah VARCHAR(50) NOT NULL
)

CREATE TABLE MINYAK_MENTAH (
    KdProdMinyak INT IDENTITY(1,1) PRIMARY KEY,
    NamaMinyak VARCHAR(50) NOT NULL,
    APIGravity FLOAT NOT NULL,
    PersenBelerang FLOAT NOT NULL,
    KdSitusPengeboran INT NOT NULL,
    CONSTRAINT FK_KdSitusMinyakMINYAKMENTAH FOREIGN KEY (KdSitusPengeboran)
        REFERENCES RIG_PENGEBORAN (KdSitusPengeboran) ON DELETE NO ACTION ON UPDATE NO ACTION,
)

CREATE TABLE PRODUK_TAMBANG (
    KdProdTambang INT IDENTITY(1,1) PRIMARY KEY,
    NamaProduk VARCHAR(50) NOT NULL,
    JenisTambang VARCHAR(50) NOT NULL
)

CREATE TABLE UNSUR (
    KdUnsur INT IDENTITY(1,1) PRIMARY KEY,
    NamaUnsur VARCHAR(50) NOT NULL
)

CREATE TABLE dimanfaatkan_oleh (
    KdSitus INT NOT NULL,
    KdPerusahaan INT NOT NULL,
    PRIMARY KEY(KdSitus, KdPerusahaan),
    CONSTRAINT FK_KdSitusDIMANFAATKANOLEH FOREIGN KEY (KdSitus)
        REFERENCES SITUS_SDA (KdSitus) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT FK_KdPerusahaanDIMANFAATKANOLEH FOREIGN KEY (KdPerusahaan)
        REFERENCES PERUSAHAAN (KdPerusahaan) ON DELETE NO ACTION ON UPDATE NO ACTION,
)

CREATE TABLE dimiliki_oleh (
    KdPerusahaan INT NOT NULL,
    KdIzin INT NOT NULL,
    PRIMARY KEY(KdPerusahaan, KdIzin),
    NoIzin INT NOT NULL,
    MasaBerlakuHari INT NOT NULL,
    TanggalDiperoleh DATE NOT NULL,
    CONSTRAINT FK_KdPerusahaanDIMILIKIOLEH FOREIGN KEY (KdPerusahaan)
        REFERENCES PERUSAHAAN (KdPerusahaan) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT FK_KdIzinDIMILIKIOLEH FOREIGN KEY (KdIzin)
        REFERENCES IZIN_USAHA (KdIzin) ON DELETE NO ACTION ON UPDATE NO ACTION,
)

CREATE TABLE menjalin (
    KdPerusahaan INT NOT NULL,
    KdKS INT NOT NULL,
    PRIMARY KEY(KdPerusahaan, KdKS),
    StatusKeanggotaan VARCHAR(20) NOT NULL,
    CONSTRAINT FK_KdPerusahaanMENJALIN FOREIGN KEY (KdPerusahaan)
        REFERENCES PERUSAHAAN (KdPerusahaan) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT FK_KdKSMENJALIN FOREIGN KEY (KdKS)
        REFERENCES KERJASAMA (KdKS) ON DELETE NO ACTION ON UPDATE NO ACTION,
)

CREATE TABLE menghasilkan_produk_hutan (
    KdSitusHutan INT NOT NULL, 
    KdProdHutan INT NOT NULL,
    PRIMARY KEY(KdSitusHutan, KdProdHutan),
    CONSTRAINT FK_KdSitusHutanMENGHASILKANHUTAN FOREIGN KEY (KdSitusHutan)
        REFERENCES HUTAN (KdSitusHutan) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT FK_KdProdHutanMENGHASILKANHUTAN FOREIGN KEY (KdProdHutan)
        REFERENCES PRODUK_PERHUTANAN (KdProdHutan) ON DELETE NO ACTION ON UPDATE NO ACTION,
)

CREATE TABLE menghasilkan_produk_kebun (
    KdSitusKebun INT NOT NULL, 
    KdProdKebun INT NOT NULL,
    PRIMARY KEY(KdSitusKebun, KdProdKebun),
    CONSTRAINT FK_KdSitusKebunMENGHASILKANKEBUN FOREIGN KEY (KdSitusKebun)
        REFERENCES KEBUN (KdSitusKebun) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT FK_KdProdKebunMENGHASILKANKEBUN FOREIGN KEY (KdProdKebun)
        REFERENCES PRODUK_PERKEBUNAN (KdProdKebun) ON DELETE NO ACTION ON UPDATE NO ACTION,
)

CREATE TABLE menghasilkan_produk_tambang  (
    KdSitusTambang INT NOT NULL,
    KdProdTambang INT NOT NULL,
    PRIMARY KEY(KdSitusTambang, KdProdTambang),
    CONSTRAINT FK_KdSitusTambangMENGHASILKANKEBUN FOREIGN KEY (KdSitusTambang)
        REFERENCES TAMBANG (KdSitusTambang) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT FK_KdProdTambangMENGHASILKANKEBUN FOREIGN KEY (KdProdTambang)
        REFERENCES PRODUK_TAMBANG (KdProdTambang) ON DELETE NO ACTION ON UPDATE NO ACTION,
)

CREATE TABLE mengandung (
    KdProdTambang INT NOT NULL,
    KdUnsur INT NOT NULL,
    PRIMARY KEY(KdProdTambang, KdUnsur),
    Kadar FLOAT NOT NULL,
    Satuan VARCHAR (20) NOT NULL,
    CONSTRAINT FK_KdProdTambangMENGANDUNG FOREIGN KEY (KdProdTambang)
        REFERENCES PRODUK_TAMBANG (KdProdTambang) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT FK_KdUnsurMENGANDUNG FOREIGN KEY (KdUnsur)
        REFERENCES UNSUR (KdUnsur) ON DELETE NO ACTION ON UPDATE NO ACTION,
)

GO
-- !SECTION Done || Define relational tables